spring:
  profiles:
    active: local
    group:
      local: db-local
      server: db-server
    include:
      - db
      - oauth
      - s3
      - jwt
      - security

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}

  #새로운 oauth2.0
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${BASE_URL_BACK}/login/oauth2/code/google    # 인증 완료 후 인가 코드를 받을 URI
            authorization-grant-type: authorization_code
            scope: profile, email    # 인가 후 받아올 사용자 정보 범위

          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${BASE_URL_BACK}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email

          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET}
            redirect-uri: ${BASE_URL_BACK}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image


        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: kakao_account

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    info:
      title: 하마하마 API Server
      description: 녹음하마 요약하마
      version: 0.0.1

cloud:
  aws:
    s3:
      bucket: p22d105s3
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret-key: ${JWT_SECRET_KEY}