spring:
  profiles:
    active: local
    group:
      local: db-local
      server: db-server
    include:
      - db

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}

springdoc:
  api-docs:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    info:
      title: ???? API Server
      description: ???? ????
      version: 0.0.1