spring:
  profiles:
    active: local
    group:
      local: db-local
      server: db-server
    include:
      - db
      - oauth

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    client-id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_SECRET}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_SECRET}
    url:
      auth: https://accounts.google.com/o/oauth2/v2/auth
      api: https://www.googleapis.com/oauth2/v3/userinfo
      token: https://oauth2.googleapis.com/token
      scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email


springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    info:
      title: 하마하마 API Server
      description: 녹음하마 요약하마
      version: 0.0.1